<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Abstractions" Version="2.3.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SistemaTienda.DAL\SistemaTienda.DAL.csproj" />
    <ProjectReference Include="..\SistemaTienda.DTO\SistemaTienda.DTO.csproj" />
    <ProjectReference Include="..\SistemaTienda.Exceptions\SistemaTienda.Exceptions.csproj" />
    <ProjectReference Include="..\SistemaTienda.Model\SistemaTienda.Model.csproj" />
    <ProjectReference Include="..\SistemaTienda.Utility\SistemaTienda.Utility.csproj" />
  </ItemGroup>

</Project>
